name: Actualizacion Automatica desde Google Sheets

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-file:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Clonar el repositorio
      uses: actions/checkout@v4

    - name: Descargar Excel directamente
      run: |
        curl -L -o tareas.xlsx "https://google.com"

    - name: Confirmar y subir cambios a GitHub
      run: |
        git config --local user.email "github-actions[bot]@://github.com"
        git config --local user.name "github-actions[bot]"
        git add tareas.xlsx
        git diff --quiet && git diff --staged --quiet || (git commit -m "Actualización automática de tareas.xlsx" && git push)
